#replicaset-definition.yml - Replicaset Sample YAML

apiVersion:  apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector: 
    # POD label to map to this replicaset
    matchLabels:
      app: front-end

  template: 
    # POD definition
    metadata: 
        name: myapp-pod
        labels:
          app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx