apiVersion: v1
kind: Service
metadata:
  name: back-end
  labels:
    app: myapp-backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 
      port: 80
       
  selector:
    app: myapp
    type: back-end